name       : gtest
version    : 1.8.0
release    : 1
source     :
    - https://github.com/google/googletest/archive/release-1.8.0.tar.gz : 58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8
license    : BSD-3-Clause
component  : programming
summary    : Google's C++ test framework.
description: |
    Google's C++ test framework.
patterns   :
    - /usr/lib64
setup      : |
    sed -i 's/DESTINATION lib/DESTINATION lib64/' google{mock,test}/CMakeLists.txt
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
