name       : gtest
version    : 1.8.1
release    : 2
source     :
    - https://github.com/google/googletest/archive/release-1.8.1.tar.gz : 9bf1fe5182a604b4135edc1a425ae356c9ad15e9b23f9f12a02e80184c3a249c
license    : BSD-3-Clause
component  : programming.tools
summary    : Google's C++ test framework.
description: |
    Google's C++ test framework.
patterns   :
    - /usr/lib64
setup      : |
    sed -i 's/DESTINATION lib/DESTINATION lib64/' google{mock,test}/CMakeLists.txt
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
