name       : gtest
version    : 1.11.0
release    : 5
source     :
    - https://github.com/google/googletest/archive/release-1.11.0.tar.gz : b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5
homepage   : https://google.github.io/googletest/
license    : BSD-3-Clause
component  : programming.tools
summary    : Google's C++ test framework
description: |
    GoogleTest is Google’s C++ testing and mocking framework.
patterns   :
    - /usr/lib64
setup      : |
    sed -i 's/DESTINATION lib/DESTINATION lib64/' google{mock,test}/CMakeLists.txt
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
